import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientWrapper from "./components/layout/client-wrapper";
import Footer from "./components/layout/footer";
import Header from "./components/layout/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={inter.className}>
          <ClientWrapper>
            <Header />
            <main className="min-h-screen">{children}</main>
            <Footer />
          </ClientWrapper>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
